/**
 * Role-based access control — consolidated role isolation tests.
 *
 * Runs in the "guest" project (no pre-authenticated state).
 * Each test logs in as a specific role and verifies it cannot access
 * routes belonging to other roles. ProtectedRoute redirects wrong-role
 * users to their own dashboard.
 *
 * Replaces scattered "cannot access X routes" tests that were duplicated
 * across auth, family-flow, purchaser-flow, and delivery-flow specs.
 */
import { test, expect } from "@playwright/test";

/**
 * Matrix of (role, forbiddenRoute, expectedRedirectPattern).
 *
 * Roles use storageState files generated by global-setup.
 * Delivery redirects to /delivery; all others redirect to /dashboard.
 */
const GUARDS: { role: string; route: string; redirect: RegExp }[] = [
  // Admin cannot access non-admin routes
  { role: "admin", route: "/referrer/families", redirect: /\/dashboard/ },
  { role: "admin", route: "/family/dashboard", redirect: /\/dashboard/ },
  { role: "admin", route: "/purchaser/assigned-gifts", redirect: /\/dashboard/ },
  { role: "admin", route: "/delivery", redirect: /\/dashboard/ },

  // Referrer cannot access admin, family, purchaser, delivery routes
  { role: "referrer", route: "/admin/referrers", redirect: /\/dashboard/ },
  { role: "referrer", route: "/family/dashboard", redirect: /\/dashboard/ },
  { role: "referrer", route: "/purchaser/assigned-gifts", redirect: /\/dashboard/ },
  { role: "referrer", route: "/delivery", redirect: /\/dashboard/ },

  // Family cannot access admin, referrer, purchaser, delivery routes
  { role: "family", route: "/admin/referrers", redirect: /\/dashboard/ },
  { role: "family", route: "/referrer/families", redirect: /\/dashboard/ },
  { role: "family", route: "/purchaser/assigned-gifts", redirect: /\/dashboard/ },
  { role: "family", route: "/delivery", redirect: /\/dashboard/ },

  // Purchaser cannot access admin, referrer, family, delivery routes
  { role: "purchaser", route: "/admin/wishes", redirect: /\/dashboard/ },
  { role: "purchaser", route: "/referrer/dashboard", redirect: /\/dashboard/ },
  { role: "purchaser", route: "/family/dashboard", redirect: /\/dashboard/ },
  { role: "purchaser", route: "/delivery", redirect: /\/dashboard/ },

  // Delivery cannot access admin, referrer, family, purchaser routes
  { role: "delivery", route: "/admin/families", redirect: /\/dashboard/ },
  { role: "delivery", route: "/referrer/dashboard", redirect: /\/dashboard/ },
  { role: "delivery", route: "/family/dashboard", redirect: /\/dashboard/ },
  { role: "delivery", route: "/purchaser/assigned-gifts", redirect: /\/dashboard/ },
];

test.describe("Role-based access control", () => {
  for (const { role, route, redirect } of GUARDS) {
    test(`${role} cannot access ${route}`, async ({ browser }) => {
      const context = await browser.newContext({
        storageState: `storage/${role}.json`,
      });
      const page = await context.newPage();

      await page.goto(route);
      await page.waitForURL(redirect, { timeout: 10_000 });

      await context.close();
    });
  }

  test("unauthenticated user accessing protected route redirects to login", async ({
    browser,
  }) => {
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto("/admin/referrers");
    await expect(page).toHaveURL(/\/login/);

    await context.close();
  });
});
