import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright configuration for end-to-end tests.
 *
 * Tests run against the Docker Compose stack (Traefik proxy at localhost:80).
 * Chromium only — sufficient for e2e validation.
 *
 * globalSetup seeds the database via the CSV import API so all tests have
 * realistic hierarchical data and known login credentials.
 */
export default defineConfig({
  testDir: "./tests",
  fullyParallel: false, // tests share seed data; run serially
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,

  /* Timeouts — lazy-loaded routes + API calls can be slow in Docker */
  timeout: 30_000,
  expect: { timeout: 10_000 },

  /* Global setup: seed DB + generate storageState files */
  globalSetup: "./helpers/global-setup",

  use: {
    baseURL: "http://localhost",
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },

  /* Role-specific projects that start authenticated via storageState files.
   * storageState files are generated by globalSetup (helpers/global-setup.ts).
   *
   * testMatch restricts which files each project runs:
   *   - admin  → seed, admin-crud, csv-upload
   *   - referrer → referrer-flow
   *   - family → family-flow
   *   - guest → auth, invite-flow, password-reset (need unauthenticated state)
   */
  projects: [
    {
      name: "admin",
      testMatch: /tests\/(00-seed|admin-crud|csv-upload|display-name)\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: "storage/admin.json",
      },
    },
    {
      name: "referrer",
      testMatch: /tests\/referrer-flow\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: "storage/referrer.json",
      },
    },
    {
      name: "family",
      testMatch: /tests\/family-flow\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        storageState: "storage/family.json",
      },
    },
    /* Unauthenticated project for auth, invite, and password-reset flows */
    {
      name: "guest",
      testMatch: /tests\/(auth|invite-flow|password-reset)\.spec\.ts/,
      use: {
        ...devices["Desktop Chrome"],
      },
    },
  ],

  /* Reporter: list + HTML on failure */
  reporter: [
    ["list"],
    ["html", { outputFolder: "playwright-report", open: "on-failure" }],
  ],
});
