import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright configuration for end-to-end tests.
 *
 * Tests run against the Docker Compose stack (Traefik proxy at localhost:80).
 * Chromium only — sufficient for e2e validation.
 *
 * Single project with full parallelism. Each test file is self-contained and
 * creates its own data. Tests that need authenticated sessions create browser
 * contexts with storageState files (generated by global-setup).
 *
 * globalSetup seeds the auth accounts needed for storageState + login tests.
 * Everything else (families, people, wishes) is created per-scenario.
 */
export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 16,

  /* Timeouts — lazy-loaded routes + API calls can be slow in Docker */
  timeout: 30_000,
  expect: { timeout: 10_000 },

  /* Global setup: seed auth accounts + generate storageState files */
  globalSetup: "./helpers/global-setup",

  use: {
    baseURL: "http://localhost",
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },

  /* Single project — tests create their own browser contexts with storageState as needed.
   * Run file subsets with: npx playwright test tests/admin-*.spec.ts
   */
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],

  /* Reporter: list + HTML on failure */
  reporter: [
    ["list"],
    ["html", { outputFolder: "playwright-report", open: "on-failure" }],
  ],
});
