"""add users table and role enum

Revision ID: 0002_add_users
Revises: 2ec0a526d649
Create Date: 2026-06-24
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002_add_users"
down_revision: Union[str, None] = "2ec0a526d649"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clean up any partial migration artifacts first (idempotent)
    op.execute("DROP TABLE IF EXISTS password_reset_tokens CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TYPE IF EXISTS user_role")

    # Create enum
    op.execute("CREATE TYPE user_role AS ENUM ('admin', 'referrer', 'family')")

    # Create users table
    op.execute(
        """CREATE TABLE users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR(120) NOT NULL,
            hashed_password VARCHAR(255) NOT NULL,
            role user_role NOT NULL,
            referrer_id INTEGER REFERENCES referrer(id) ON DELETE SET NULL,
            family_id INTEGER REFERENCES family(id) ON DELETE SET NULL,
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMPTZ DEFAULT now()
        )"""
    )
    op.execute("CREATE INDEX ix_users_id ON users (id)")
    op.execute("CREATE UNIQUE INDEX ix_users_email ON users (email)")

    # Create password_reset_tokens table
    op.execute(
        """CREATE TABLE password_reset_tokens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            token VARCHAR(255) NOT NULL UNIQUE,
            expires_at TIMESTAMPTZ NOT NULL,
            used BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMPTZ DEFAULT now()
        )"""
    )
    op.execute("CREATE INDEX ix_password_reset_tokens_id ON password_reset_tokens (id)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS password_reset_tokens CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TYPE IF EXISTS user_role")
