"""add pickup_window to family

Revision ID: 2146c29b3122
Revises: 364525cb1d99
Create Date: 2026-07-31 03:08:49.069702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2146c29b3122"
down_revision: Union[str, None] = "364525cb1d99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("family", sa.Column("pickup_window", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family", "pickup_window")
    # ### end Alembic commands ###
