"""new initial state

Revision ID: 2ec0a526d649
Revises: 
Create Date: 2026-06-22 16:44:16.611484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec0a526d649'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('family_limit', sa.SmallInteger(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrer_id'), 'referrer', ['id'], unique=False)

    #Not generated, but I think this is the right spot to throw the orphanage
    op.execute(
        "INSERT INTO referrer (id, name, family_limit, email, phone_number) "
        "VALUES (1, 'Empty Referrer', 32000, 'orphan@kindness.is-magic', '000-000-0000')"
    )

    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('family_name', sa.String(length=40), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('family_wish', sa.String(length=400), nullable=False),
    sa.Column('contact_name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['referrer.id'], ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_id'), 'family', ['id'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('practical_wish', sa.String(length=400), nullable=False),
    sa.Column('fun_wish', sa.String(length=400), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_family_id'), table_name='family')
    op.drop_table('family')
    op.drop_index(op.f('ix_referrer_id'), table_name='referrer')
    op.drop_table('referrer')
    # ### end Alembic commands ###
