"""initial

Revision ID: 3aded6221803
Revises: 
Create Date: 2026-07-29 02:09:23.228078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aded6221803'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Tables with no inter-dependencies first ---
    op.create_table('email_preferences',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_email_preferences_email'), 'email_preferences', ['email'], unique=False)

    # --- referrer before family (family FK → referrer)
    # Created WITHOUT FK to users (cyclic: referrer→users→family→referrer)
    op.create_table('referrer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('family_limit', sa.SmallInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('family_invite_code', sa.String(length=10), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='referrer_approval_status', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('approved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrer_family_invite_code'), 'referrer', ['family_invite_code'], unique=True)
    op.create_index(op.f('ix_referrer_id'), 'referrer', ['id'], unique=False)

    # --- family (FK → referrer exists now)
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('family_name', sa.String(length=40), nullable=False),
    sa.Column('bio', sa.String(length=400), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), server_default='', nullable=False),
    sa.Column('family_wish', sa.String(length=400), nullable=False),
    sa.Column('contact_name', sa.String(length=40), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='family_approval_status', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['referrer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_id'), 'family', ['id'], unique=False)
    op.create_index('ix_family_referrer_id_deleted_at', 'family', ['referrer_id', 'deleted_at'], unique=False)

    # --- users (FK → referrer, FK → family — both exist now)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=True),
    sa.Column('role', sa.Enum('admin', 'referrer', 'family', name='user_role', create_constraint=True), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['referrer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # --- Deferred cyclic FK: referrer.approved_by_admin_id → users.id ---
    op.create_foreign_key(
        'fk_referrer_approved_by_admin_id',
        'referrer', 'users',
        ['approved_by_admin_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id_used_at', 'password_reset_tokens', ['user_id', 'used_at'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('practical_wish', sa.String(length=400), nullable=False),
    sa.Column('fun_wish', sa.String(length=400), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_person_family_id_deleted_at', 'person', ['family_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    op.create_table('referrer_invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('family_limit', sa.SmallInteger(), nullable=False),
    sa.Column('locked_email', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('redeemed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_by_referrer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_referrer_id'], ['referrer.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrer_invite_tokens_code'), 'referrer_invite_tokens', ['code'], unique=True)
    op.create_index(op.f('ix_referrer_invite_tokens_id'), 'referrer_invite_tokens', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_referrer_invite_tokens_id'), table_name='referrer_invite_tokens')
    op.drop_index(op.f('ix_referrer_invite_tokens_code'), table_name='referrer_invite_tokens')
    op.drop_table('referrer_invite_tokens')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_index('ix_person_family_id_deleted_at', table_name='person')
    op.drop_table('person')
    op.drop_index('ix_password_reset_tokens_user_id_used_at', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Drop deferred cyclic FK before dropping referrer
    op.drop_constraint('fk_referrer_approved_by_admin_id', 'referrer', type_='foreignkey')
    op.drop_index(op.f('ix_referrer_id'), table_name='referrer')
    op.drop_index(op.f('ix_referrer_family_invite_code'), table_name='referrer')
    op.drop_table('referrer')
    op.drop_index('ix_family_referrer_id_deleted_at', table_name='family')
    op.drop_index(op.f('ix_family_id'), table_name='family')
    op.drop_table('family')
    op.drop_index(op.f('ix_email_preferences_email'), table_name='email_preferences')
    op.drop_table('email_preferences')
    # ### end Alembic commands ###
