"""initial schema

Revision ID: 611834b4d826
Revises:
Create Date: 2026-09-26 10:00:29.086192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "611834b4d826"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deadlines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("family_info", "referrer_review", "gift_dropoff", name="deadline_type", create_constraint=True), nullable=False
        ),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum("display", "remind", "enforced", name="deadline_mode", create_constraint=True),
            server_default="display",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deadlines_id"), "deadlines", ["id"], unique=False)
    op.create_table(
        "email_preferences",
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(op.f("ix_email_preferences_email"), "email_preferences", ["email"], unique=False)
    # users is created first, before referrer and family, without its two FKs:
    # referrer.approved_by_admin_id and family.delivery_user_id point back at
    # users, so those users FKs are added after all three tables exist.
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=40), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "referrer", "family", "purchaser", "delivery", "donor", name="user_role", create_constraint=True),
            nullable=False,
        ),
        sa.Column("referrer_id", sa.Integer(), nullable=True),
        sa.Column("family_id", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "referrer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("family_limit", sa.SmallInteger(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("family_invite_code", sa.String(length=10), nullable=False),
        sa.Column(
            "approval_status",
            sa.Enum("pending", "approved", "rejected", name="referrer_approval_status", create_constraint=True),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("approved_by_admin_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["approved_by_admin_id"], ["users.id"], name="fk_referrer_approved_by_admin_id", ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrer_family_invite_code"), "referrer", ["family_invite_code"], unique=True)
    op.create_index(op.f("ix_referrer_id"), "referrer", ["id"], unique=False)
    op.create_table(
        "family",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("referrer_id", sa.Integer(), nullable=True),
        sa.Column("family_name", sa.String(length=40), nullable=False),
        sa.Column("bio", sa.String(length=400), nullable=True),
        sa.Column("address", sa.String(length=200), server_default="none", nullable=False),
        sa.Column("phone_number", sa.String(length=20), server_default="", nullable=False),
        sa.Column("contact_name", sa.String(length=40), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum("pending", "verified", "rejected", name="family_verification_status", create_constraint=True),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("pickup_window", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "wish_lock_level",
            sa.Enum("family", "referrer", "admin", name="wish_lock_level", create_constraint=True),
            server_default="family",
            nullable=False,
        ),
        sa.Column("wish_review_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wish_rejection_reason", sa.String(length=400), nullable=True),
        sa.Column("referrer_notes", sa.String(length=1000), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("delivery_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["delivery_user_id"], ["users.id"], name="fk_family_delivery_user_id", ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["referrer_id"], ["referrer.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_family_id"), "family", ["id"], unique=False)
    op.create_index("ix_family_referrer_id_deleted_at", "family", ["referrer_id", "deleted_at"], unique=False)
    op.create_foreign_key("fk_users_referrer_id", "users", "referrer", ["referrer_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("fk_users_family_id", "users", "family", ["family_id"], ["id"], ondelete="SET NULL")
    op.create_table(
        "family_claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("donor_user_id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("commitment_type", sa.Enum("gifts", "cash", name="commitment_type", create_constraint=True), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum("pending", "paid", name="claim_payment_status", create_constraint=True),
            server_default="paid",
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("zeffy_payment_id", sa.String(length=64), nullable=True),
        sa.Column("includes_groceries", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["donor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_family_claims_donor_deleted", "family_claims", ["donor_user_id", "deleted_at"], unique=False)
    op.create_index(op.f("ix_family_claims_id"), "family_claims", ["id"], unique=False)
    op.create_index(op.f("ix_family_claims_zeffy_payment_id"), "family_claims", ["zeffy_payment_id"], unique=False)
    op.create_index(
        "uq_family_claims_family_active", "family_claims", ["family_id"], unique=True, postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_password_reset_tokens_id"), "password_reset_tokens", ["id"], unique=False)
    op.create_index("ix_password_reset_tokens_user_id_used_at", "password_reset_tokens", ["user_id", "used_at"], unique=False)
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("given_name", sa.String(length=40), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "son",
                "daughter",
                "grandson",
                "granddaughter",
                "mother",
                "father",
                "grandfather",
                "grandmother",
                "aunt",
                "uncle",
                "cousin",
                "nephew",
                "niece",
                "cat",
                "dog",
                name="person_role",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=400), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_person_family_id_deleted_at", "person", ["family_id", "deleted_at"], unique=False)
    op.create_index(op.f("ix_person_id"), "person", ["id"], unique=False)
    op.create_table(
        "referrer_invite_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("family_limit", sa.SmallInteger(), nullable=False),
        sa.Column("locked_email", sa.String(length=120), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("redeemed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("redeemed_by_referrer_id", sa.Integer(), nullable=True),
        sa.Column("created_by_admin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_by_referrer_id"],
            ["referrer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrer_invite_tokens_code"), "referrer_invite_tokens", ["code"], unique=True)
    op.create_index(op.f("ix_referrer_invite_tokens_id"), "referrer_invite_tokens", ["id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=False)
    op.create_table(
        "sent_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("recipient_email", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "family_invite",
                "referrer_invite",
                "password_reset",
                "family_pending",
                "family_verified",
                "family_rejected",
                "referrer_approved",
                "referrer_rejected",
                "claim_confirmation",
                "admin_failure_notice",
                "payment_request",
                "payment_confirmed",
                "payment_expired",
                name="email_kind",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("sent", "failed", "reset", name="email_status", create_constraint=True), nullable=False),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sent_emails_id"), "sent_emails", ["id"], unique=False)
    op.create_index("ix_sent_emails_kind_sent", "sent_emails", ["kind", "sent_at"], unique=False)
    op.create_index("ix_sent_emails_recipient_sent", "sent_emails", ["recipient_email", "sent_at"], unique=False)
    op.create_index("ix_sent_emails_user_sent", "sent_emails", ["user_id", "sent_at"], unique=False)
    op.create_table(
        "wish",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("family_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.Enum("adult", "practical", "fun", "family", name="wish_type", create_constraint=True), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("size", sa.String(length=20), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purchased_where", sa.String(length=200), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purchaser_note", sa.String(length=400), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("((person_id IS NOT NULL) <> (family_id IS NOT NULL))", name="ck_wish_exactly_one_owner"),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_wish_family_id_deleted_at", "wish", ["family_id", "deleted_at"], unique=False)
    op.create_index(op.f("ix_wish_id"), "wish", ["id"], unique=False)
    op.create_index("ix_wish_person_id_deleted_at", "wish", ["person_id", "deleted_at"], unique=False)
    op.create_index(
        "uq_wish_family_type_active", "wish", ["family_id", "type"], unique=True, postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index(
        "uq_wish_person_type_active", "wish", ["person_id", "type"], unique=True, postgresql_where=sa.text("deleted_at IS NULL")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # This is the initial migration: downgrading it yields an empty database.
    # Don't bother — just delete the database. Raise rather than no-op so
    # alembic aborts without stamping the version to base while the tables
    # are still in place (which would break the next `alembic upgrade head`).
    raise RuntimeError("Downgrade goes to an empty database; just delete it.")
