"""removed useless stuff and added note to family member

Revision ID: 758a1901c9ae
Revises: f1a9de7b7bf8
Create Date: 2025-10-29 04:33:19.955050

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '758a1901c9ae'
down_revision = 'f1a9de7b7bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('familymember', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.drop_column('familymember', 'title')
    op.drop_column('familymember', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('familymember', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('familymember', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('familymember', 'note')
    # ### end Alembic commands ###
