"""added family_role to family members

Revision ID: aa4a4065c7c6
Revises: b64c782447bf
Create Date: 2025-11-20 00:40:41.558208

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aa4a4065c7c6'
down_revision = 'b64c782447bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('familymember', sa.Column('family_role', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('familymember', 'family_role')
    # ### end Alembic commands ###
