"""removed lower limits for optional fields

Revision ID: b64c782447bf
Revises: 758a1901c9ae
Create Date: 2025-10-29 04:55:48.365274

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b64c782447bf'
down_revision = '758a1901c9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
