"""added person stuff to item

Revision ID: ff300b4beb97
Revises: 1a31ce608336
Create Date: 2025-10-28 03:04:23.414637

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ff300b4beb97'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('given_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('item', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('practical_wish', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('fun_wish', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'fun_wish')
    op.drop_column('item', 'practical_wish')
    op.drop_column('item', 'age')
    op.drop_column('item', 'given_name')
    # ### end Alembic commands ###
