"""Read-only Zeffy API client (https://api.zeffy.com/api/v1).

Reconciles payments made on the org's dedicated sponsorship donation form
back to donor carts. Only the read endpoints are used (list/get payments,
get campaign) — the write endpoints are deliberately out of scope for v1.

* Auth: ``Authorization: Bearer <ZEFFY_API_KEY>`` (generated by the org
  owner in Settings → Integrations).
* Rate limits are per **organization** (100 req/min sliding window + 20
  req/sec burst). A single 429 is retried once after ``Retry-After``;
  outbound calls are additionally throttled to a ~3s minimum interval
  (``ZEFFY_MIN_INTERVAL_SECONDS``, read at call time so tests can set 0)
  so concurrent app activity never exhausts the shared quota.
* 401 → :class:`ZeffyAuthError` (misconfigured key); 404 → ``None`` from the
  ``get_*`` lookups. :func:`validate_configured_campaign` caches campaign
  validation successes per process; failures are never cached, so a
  corrected ``ZEFFY_CAMPAIGN_ID`` takes effect without a restart.
"""

import hmac
import logging
import os
import re
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime

import httpx

from app.config import ZEFFY_API_BASE, ZEFFY_API_KEY, ZEFFY_CAMPAIGN_ID, ZEFFY_WEBHOOK_SECRET

logger = logging.getLogger(__name__)

# Base URL of the Zeffy API (``ZEFFY_API_BASE`` env; the dev/e2e stack points
# this at the bundled mock instead of the real, org-rate-limited API).
BASE_URL = ZEFFY_API_BASE
USER_AGENT = "kindness-is-magic/1.0"
TIMEOUT_SECONDS = 10.0

# Minimum interval between outbound Zeffy calls (seconds), read at call time
# so tests can monkeypatch it to 0. The org-wide quota is shared by every
# API key of the organization — this keeps the app a good citizen even when
# several users hammer confirm/checkout.
_MIN_INTERVAL_ENV = "ZEFFY_MIN_INTERVAL_SECONDS"

# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class ZeffyError(Exception):
    """Base for all Zeffy client errors."""


class ZeffyNotConfiguredError(ZeffyError):
    """A required Zeffy setting (API key / campaign ID) is missing.

    Maps to 503 in routes — the unconfigured dev/e2e default state.
    """


class ZeffyAuthError(ZeffyError):
    """Zeffy rejected the API key (401) — misconfigured ZEFFY_API_KEY."""


class ZeffyCampaignNotFoundError(ZeffyError):
    """GET /campaigns/{id} returned 404 — ZEFFY_CAMPAIGN_ID is wrong."""


class ZeffyAPIError(ZeffyError):
    """Any other API failure (network error, or >=400 other than 401/404)."""

    def __init__(self, status_code: int, message: str):
        super().__init__(message)
        self.status_code = status_code
        self.message = message


class _ZeffyNotFound(ZeffyError):
    """Internal: 404 from a get_* lookup (public API returns None)."""


# ---------------------------------------------------------------------------
# Typed payloads (raw JSON → small dataclasses; no DB, no commits here)
# ---------------------------------------------------------------------------


@dataclass
class ZeffyBuyer:
    email: str | None = None
    first_name: str | None = None
    last_name: str | None = None
    is_corporate: bool = False
    company_name: str | None = None


@dataclass
class ZeffyPayment:
    id: str
    created: int  # unix timestamp
    amount: int  # cents
    currency: str
    status: str  # succeeded / failed / pending
    type: str  # online / manual / imported
    campaign_id: str | None = None
    description: str | None = None  # campaign title
    contact: str | None = None  # buyer contact id (UUID or None)
    buyer: ZeffyBuyer | None = None
    receipt_url: str | None = None
    refund_status: str = "none"


@dataclass
class ZeffyCampaign:
    id: str
    title: str | None = None
    url: str | None = None
    status: str | None = None
    type: str | None = None
    currency: str | None = None


@dataclass
class ZeffyPaymentPage:
    """List envelope: ``data`` / ``has_more`` / ``next_cursor`` (pass the
    cursor as ``starting_after`` for the next page)."""

    data: list[ZeffyPayment]
    has_more: bool = False
    next_cursor: str | None = None


# ---------------------------------------------------------------------------
# HTTP plumbing (per-call client; tests inject a transport below)
# ---------------------------------------------------------------------------

_transport_override: httpx.BaseTransport | None = None

_throttle_lock = threading.Lock()
_last_call_at = 0.0


def _throttle() -> None:
    """Block until the configured minimum interval has passed since the last outbound call."""
    global _last_call_at
    interval = float(os.environ.get(_MIN_INTERVAL_ENV, "3.0"))
    if interval <= 0:
        return
    with _throttle_lock:
        wait = _last_call_at + interval - time.monotonic()
        if wait > 0:
            time.sleep(wait)
        _last_call_at = time.monotonic()


def _request(method: str, path: str, *, params: dict | None = None) -> httpx.Response:
    """Perform one authenticated request with a single 429 retry.

    A fresh ``httpx.Client`` is used per call (connection reuse is
    unneeded at this volume, and it keeps the client trivially
    thread-safe). Tests point ``_transport_override`` at a MockTransport.
    """
    if not ZEFFY_API_KEY:
        raise ZeffyNotConfiguredError("ZEFFY_API_KEY is not set")

    _throttle()
    headers = {
        "Authorization": f"Bearer {ZEFFY_API_KEY}",
        "User-Agent": USER_AGENT,
        "Accept": "application/json",
    }
    transport = _transport_override
    try:
        with httpx.Client(base_url=BASE_URL, timeout=TIMEOUT_SECONDS, transport=transport) as client:
            response = client.request(method, path, params=params, headers=headers)
            if response.status_code == 429:
                retry_after = response.headers.get("Retry-After", "1")
                try:
                    delay = max(float(retry_after), 0.0)
                except ValueError:
                    delay = 1.0
                logger.warning("Zeffy rate limit hit — retrying once after %.1fs (%s %s)", delay, method, path)
                time.sleep(delay)
                response = client.request(method, path, params=params, headers=headers)
    except httpx.HTTPError as exc:
        raise ZeffyAPIError(0, f"Zeffy request failed: {exc}") from exc

    if response.status_code == 401:
        raise ZeffyAuthError("Zeffy rejected the API key (401) — check ZEFFY_API_KEY")
    if response.status_code == 404:
        raise _ZeffyNotFound(f"Zeffy resource not found: {method} {path}")
    if response.status_code >= 400:
        message = response.text[:200]
        try:
            payload = response.json()
            error = payload.get("error")
            if isinstance(error, dict) and error.get("message"):
                message = f"{error.get('code', 'error')}: {error['message']}"
        except (ValueError, AttributeError):
            pass
        raise ZeffyAPIError(response.status_code, f"Zeffy API error ({response.status_code}): {message}")
    return response


# ---------------------------------------------------------------------------
# Response parsing
# ---------------------------------------------------------------------------


def _parse_buyer(raw: dict | None) -> ZeffyBuyer | None:
    if not raw:
        return None
    return ZeffyBuyer(
        email=raw.get("email"),
        first_name=raw.get("first_name"),
        last_name=raw.get("last_name"),
        is_corporate=bool(raw.get("is_corporate", False)),
        company_name=raw.get("company_name"),
    )


def parse_payment(raw: dict) -> ZeffyPayment:
    return ZeffyPayment(
        id=str(raw.get("id", "")),
        created=int(raw.get("created", 0)),
        amount=int(raw.get("amount", 0)),
        currency=raw.get("currency") or "",
        status=raw.get("status") or "",
        type=raw.get("type") or "",
        campaign_id=raw.get("campaign_id"),
        description=raw.get("description"),
        contact=raw.get("contact"),
        buyer=_parse_buyer(raw.get("buyer")),
        receipt_url=raw.get("receipt_url"),
        refund_status=raw.get("refund_status") or "none",
    )


# ---------------------------------------------------------------------------
# Read endpoints
# ---------------------------------------------------------------------------


def list_payments(
    *,
    campaign_id: str | None = None,
    status: str | None = None,
    created_gte: datetime | None = None,
    starting_after: str | None = None,
    limit: int = 10,
) -> ZeffyPaymentPage:
    """GET /api/v1/payments — one page of the (newest-first) payment list.

    ``created_gte`` is sent as the unix ``created[gte]`` filter; pass
    ``starting_after=page.next_cursor`` for the next page.
    """
    params: dict = {"limit": limit}
    if campaign_id:
        params["campaign"] = campaign_id
    if status:
        params["status"] = status
    if created_gte is not None:
        params["created[gte]"] = int(created_gte.timestamp())
    if starting_after:
        params["starting_after"] = starting_after
    response = _request("GET", "/api/v1/payments", params=params)
    body = response.json()
    return ZeffyPaymentPage(
        data=[parse_payment(p) for p in body.get("data", [])],
        has_more=bool(body.get("has_more", False)),
        next_cursor=body.get("next_cursor"),
    )


def get_payment(payment_id: str) -> ZeffyPayment | None:
    """GET /api/v1/payments/{id} — None when Zeffy returns 404."""
    try:
        response = _request("GET", f"/api/v1/payments/{payment_id}")
    except _ZeffyNotFound:
        return None
    return parse_payment(response.json())


def get_campaign(campaign_id: str) -> ZeffyCampaign | None:
    """GET /api/v1/campaigns/{id} — None when Zeffy returns 404."""
    try:
        response = _request("GET", f"/api/v1/campaigns/{campaign_id}")
    except _ZeffyNotFound:
        return None
    raw = response.json()
    return ZeffyCampaign(
        id=str(raw.get("id", "")),
        title=raw.get("title"),
        url=raw.get("url"),
        status=raw.get("status"),
        type=raw.get("type"),
        currency=raw.get("currency"),
    )


# ---------------------------------------------------------------------------
# One-time validation of the configured campaign
# ---------------------------------------------------------------------------

# Successful validations cached per process (campaign_id → ZeffyCampaign).
# Failures are deliberately never cached: each call retries, so a corrected
# ZEFFY_CAMPAIGN_ID takes effect without a restart.
_campaign_cache: dict[str, ZeffyCampaign] = {}
_campaign_cache_lock = threading.Lock()


def validate_configured_campaign() -> ZeffyCampaign:
    """Validate ``ZEFFY_CAMPAIGN_ID`` once per process (success cached).

    First triggered by the checkout endpoint, so a typo fails loudly at the
    donor's first checkout. Raises:

    * :class:`ZeffyNotConfiguredError` — no API key or campaign ID set.
    * :class:`ZeffyAuthError` — 401 (bad key).
    * :class:`ZeffyCampaignNotFoundError` — the ID doesn't exist in Zeffy.
    """
    if not ZEFFY_API_KEY:
        raise ZeffyNotConfiguredError("ZEFFY_API_KEY is not set")
    if not ZEFFY_CAMPAIGN_ID:
        raise ZeffyNotConfiguredError("ZEFFY_CAMPAIGN_ID is not set")
    with _campaign_cache_lock:
        cached = _campaign_cache.get(ZEFFY_CAMPAIGN_ID)
    if cached is not None:
        return cached
    campaign = get_campaign(ZEFFY_CAMPAIGN_ID)
    if campaign is None:
        raise ZeffyCampaignNotFoundError("Zeffy campaign ID not found — check ZEFFY_CAMPAIGN_ID")
    with _campaign_cache_lock:
        _campaign_cache[ZEFFY_CAMPAIGN_ID] = campaign
    return campaign


def clear_campaign_cache() -> None:
    """Test helper: drop the per-process campaign validation cache."""
    with _campaign_cache_lock:
        _campaign_cache.clear()


# ---------------------------------------------------------------------------
# Webhook signature verification (POST /api/zeffy/webhook)
#
# Zeffy signs every delivery: ``Zeffy-Signature: t=<unix>,v1=<hex>`` where
# ``v1`` = hex HMAC-SHA256 of ``{t}.{rawBody}`` keyed by the webhook secret
# (``whsec_...``). Each retry is re-signed with a fresh ``t``.
# ---------------------------------------------------------------------------

WEBHOOK_SIGNATURE_TOLERANCE_SECONDS = 300  # the spec's recommended 5-minute replay guard


def parse_webhook_signature(header_value: str | None) -> tuple[int, str] | None:
    """Parse ``t=<unix>,v1=<hex>`` → ``(t, v1)``, or None when malformed."""
    if not header_value:
        return None
    fields: dict[str, str] = {}
    for part in header_value.split(","):
        if "=" not in part:
            return None
        key, value = part.split("=", 1)
        fields[key.strip()] = value.strip()
    t_raw = fields.get("t")
    v1 = fields.get("v1")
    if not t_raw or not v1:
        return None
    try:
        t = int(t_raw)
    except ValueError:
        return None
    if not re.fullmatch(r"[0-9a-fA-F]+", v1):
        return None
    return t, v1


def verify_webhook_signature(t: int, v1: str, raw_body: bytes) -> bool:
    """Constant-time HMAC-SHA256 check of ``{t}.{rawBody}`` under the configured secret.

    Always hashes the raw bytes received — never a re-serialized parse.
    """
    if not ZEFFY_WEBHOOK_SECRET:
        return False
    expected = hmac.new(ZEFFY_WEBHOOK_SECRET.encode(), f"{t}.".encode() + raw_body, "sha256").hexdigest()
    return hmac.compare_digest(expected, v1)


def webhook_timestamp_is_fresh(t: int, now: float | None = None) -> bool:
    """Replay guard: |now - t| within the 5-minute tolerance."""
    now = now if now is not None else time.time()
    return abs(now - t) <= WEBHOOK_SIGNATURE_TOLERANCE_SECONDS


# ---------------------------------------------------------------------------
# Cart reconciliation
# ---------------------------------------------------------------------------


@dataclass
class CartPaymentMatch:
    """Result of reconciling a donor's cart against the campaign's payments.

    * ``payment`` — the newest succeeded, exact-amount, USD, same-buyer-email
      payment (the auto-apply candidate); None when nothing matches.
    * ``other_payments`` — the donor's other succeeded payments on the
      campaign (different amount or non-USD), newest first — served for the
      confirm endpoint's mismatch branch from the same call (the org's rate
      budget is shared; never make a second Zeffy call for it).
    """

    payment: ZeffyPayment | None = None
    other_payments: list[ZeffyPayment] = field(default_factory=list)


def find_cart_payment(donor_email: str, expected_amount_cents: int, created_gte: datetime) -> CartPaymentMatch:
    """Find the donor's payment matching the current cart total.

    One ``list_payments`` call on the configured campaign (status
    ``succeeded``, ``created >= created_gte``, ``limit=100`` — the API's
    newest-first ordering makes this the 100 most recent succeeded payments
    after the window anchor); matching is done client-side. The anchor
    (oldest pending cash claim's ``created_at``) keeps stale unmatched
    payments from re-matching a rebuilt cart.
    """
    if not ZEFFY_API_KEY:
        raise ZeffyNotConfiguredError("ZEFFY_API_KEY is not set")
    if not ZEFFY_CAMPAIGN_ID:
        raise ZeffyNotConfiguredError("ZEFFY_CAMPAIGN_ID is not set")

    page = list_payments(campaign_id=ZEFFY_CAMPAIGN_ID, status="succeeded", created_gte=created_gte, limit=100)

    email = donor_email.strip().lower()
    matches: list[ZeffyPayment] = []
    others: list[ZeffyPayment] = []
    for payment in page.data:
        buyer = payment.buyer
        if buyer is None or not buyer.email:
            continue
        if buyer.email.strip().lower() != email:
            continue
        if payment.amount == expected_amount_cents and payment.currency == "usd":
            matches.append(payment)
        else:
            others.append(payment)

    matches.sort(key=lambda p: p.created, reverse=True)
    others.sort(key=lambda p: p.created, reverse=True)
    return CartPaymentMatch(payment=matches[0] if matches else None, other_payments=others)
